### ISSUE TITLE
No image output on /yolov5_video

### ISSUE THREAD

**Issue by Ponkyao** [Alex-Beh/yolov5_ros#1]
Hello, I have some problems in jetson agx xavier ,  I changed the topic of camera,   my camera is 1920x1080.
Then I meet Resolution of the video : 640 x 480, and it stays here.
How do I solve this?  Thanks

nvidia@nvidia-desktop:~/Desktop/yolov5_ros_trt$ roslaunch yolov5_ros yolov5_ros.launch 
... logging to /home/nvidia/.ros/log/cec609f4-034d-11ed-a80b-845cf327638e/roslaunch-nvidia-desktop-11983.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://nvidia-desktop:38035/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.13
 * /yolov5_gesture/batch_size: 1
 * /yolov5_gesture/conf_thresh: 0.8
 * /yolov5_gesture/model_name: /home/nvidia/Desk...
 * /yolov5_gesture/nms_threshold: 0.5

NODES
  /
    yolov5_gesture (yolov5_ros/yolov5_gesture)

ROS_MASTER_URI=http://localhost:11311

process[yolov5_gesture-1]: started with pid [12017]
[ INFO] [1657789306.685629840]: ----> engine_name: /home/nvidia/Desktop/yolov5_ros_trt/src/yolov5_ros/model/yolov5s.engine
[ INFO] [1657789306.690955678]: ----> nms_threshold: 0.500000
[ INFO] [1657789306.691165737]: ----> conf_thresh: 0.800000
[ INFO] [1657789306.691321457]: ----> batch_size: 1
m_batch_size: 1 --- data_size: 1228800!!!
Resolution of the video : 640 x 480

**Comment by Alex-Beh** [comment]
For some reason, the printout is useless and the parameters is not being used in the program. Feel free to do PR to remove [this part](https://github.com/Alex-Beh/yolov5_ros/blob/e1bd85cd244f28810173a9949a898f2980ae4329/src/video_inteference_yolov5.cpp#L109). From line 102 to line 109.

The actual parameter which determine the output resolution is [INPUT_W & INPUT_H](https://github.com/Alex-Beh/yolov5_ros/blob/e1bd85cd244f28810173a9949a898f2980ae4329/src/video_inteference_yolov5.cpp#L133). The `INPUT_W` and `INPUT_H` parameters can be changed [here](https://github.com/Alex-Beh/yolov5_ros/blob/e1bd85cd244f28810173a9949a898f2980ae4329/include/yolov5_ros/yololayer.h#L29).

**Comment by Ponkyao** [comment]
Thank you for your prompt reply.Please forgive me for my poor English. 
I changed  INPUT_W and INPUT_H parameters.And removed [this part](https://github.com/Alex-Beh/yolov5_ros/blob/e1bd85cd244f28810173a9949a898f2980ae4329/src/video_inteference_yolov5.cpp#L109). From line 102 to line 109.

But again, once you print out the "m_batch_size: 1 --- data_size: 6220800!!!", the program will be parked here.
And the rostopic echo /yolov5_video no messages  .

process[yolov5_gesture-1]: started with pid [12017]
[ INFO] [1657789306.685629840]: ----> engine_name: /home/nvidia/Desktop/yolov5_ros_trt/src/yolov5_ros/model/yolov5s.engine
[ INFO] [1657789306.690955678]: ----> nms_threshold: 0.500000
[ INFO] [1657789306.691165737]: ----> conf_thresh: 0.800000
[ INFO] [1657789306.691321457]: ----> batch_size: 1
m_batch_size: 1 --- data_size: 6220800!!!

**Comment by Alex-Beh** [comment]
Can you attach the screenshot from your rqt_graph? or the terminal screenshot from rosnode info.

**Comment by Ponkyao** [comment]
![Screenshot from 2022-07-15 13-16-25](https://user-images.githubusercontent.com/90617563/179155800-e70c9e5d-ceaa-4947-b641-8c21729fc447.png)

**Comment by Alex-Beh** [comment]
You can try change the [following line](https://github.com/Alex-Beh/yolov5_ros/blob/e1bd85cd244f28810173a9949a898f2980ae4329/launch/yolov5_ros.launch#L8) to
`        <remap from="/usb_cam/image_raw" to="/camera/image"/>
`.

**Comment by Ponkyao** [comment]
I received the image by /yolov5_video, and cahnged  " const char *class_name[80]".
But as with the original input, there is no prediction information and prediction box.

**Comment by Ponkyao** [comment]
I'm sorry to ask if I can add your Twitter account. My Twitter is ponnkyao.

**Comment by Ponkyao** [comment]
Thank you,I received the image by /yolov5_video
